### ISSUE TITLE
Modern meteor shouldn't need this anymore

### ISSUE THREAD

**Issue by Haroenv** [devwax/react-instantsearch-meteor#1]
seen in https://github.com/meteor/meteor/issues/6890#issuecomment-342496723: they now support the object form (the issue is closed). Do you confirm that?

**Comment by devwax** [comment]
Yes, I confirm that the issue is resolved in [1.6.1](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.6.1-rc.2). Thanks for the heads up! I'll deprecate / add a note to the readme in the npm module to let others know. Thanks.

**Comment by Haroenv** [comment]
Awesome news 👌
